# Database configuration
# Connection string is in Go pq driver format:
# host=<host> port=<port> user=<databaseUser>
# password=<databaseUSerPassword> dbname=<databaseName>

[database]

connection_string = "host=localhost port=5432 user=postgres password=gurpreet dbname=match_db sslmode='disable'"
max_idle_connections=5
max_open_connections=20
connection_max_lifetime="60s"
driver_name="postgres"

# HTTP server configuration
[http]

server_address=":8080"